In [25]:
import init_sol as init
import voisinage as v
import numpy as np
import os
import pandas as pd
import time

In [26]:
pb = init.Pb("instances/gap1.txt", 3)
sol = init.sol_gloutonne(pb)
val = pb.evaluate(sol)
print(val, sol)
print(init.sol_gloutonne_2(pb))
pb.x
somme = np.sum([pb.c[pb.x[t],t] for t in range(pb.t)])
print(somme)
sol = init.sol_gloutonne_stoch(pb)
val = pb.evaluate(sol)
print(val, sol)


314 [1, 4, 2, 4, 0, 0, 3, 1, 1, -1, 2, 2, 3, 4, 1]
[ 1  4  2  4  0  0  3  1  1 -1  2  2  3  4  1]
314
299 [1, 4, -1, -1, -1, 4, -1, -1, -1, -1, -1, -1, -1, -1, 3]


In [27]:
pb = init.Pb("instances/gap12.txt", 4)

print(v.montee_iterMax(pb,init.sol_gloutonne_2,v.montee_un_pas_swap,20))

pb = init.Pb("instances/gap12.txt", 4)
v.montee_timeMax(pb,init.sol_gloutonne_2,v.montee_un_pas_swap,2)

Exception in thread Thread-400 (montee):
Traceback (most recent call last):
  File "d:\Program\python\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\ddesa\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "d:\Program\python\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\ddesa\OneDrive\Documents\Dimitri\scolarité\ENSTA-MPRO\MH\projet-Meta\voisinage.py", line 160, in montee
    opt_local = fn_un_pas(pb, critere)
                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: montee_un_pas_swap() takes 1 positional argument but 2 were given


initialisation..
[2 2 9 3 4 4 2 9 8 8 1 8 9 2 0 9 2 1 3 0 0 9 6 1 9 3 4 3 6 0 4 0 9 2 8 6 3
 6 8 5 1 5 8 2 0 7 2 3 0 8 9 4 3 6 6 5 5 1 2 6]
(np.int64(1393), np.int64(1293), array([2, 2, 3, 3, 3, 5, 2, 9, 8, 8, 1, 8, 9, 1, 0, 9, 2, 1, 9, 0, 5, 9,
       6, 1, 9, 5, 4, 3, 6, 6, 4, 0, 4, 2, 3, 1, 3, 4, 5, 8, 2, 6, 0, 2,
       8, 7, 2, 4, 0, 8, 9, 9, 3, 0, 6, 0, 8, 6, 2, 6]), 13)


(np.int64(1293), 0.006979942321777344)

In [28]:
fn_initialisation = init.sol_gloutonne_2
fn_un_pas = v.un_pas_swap
timeMax = 20
critere = 'max'
results = {}

for file in os.listdir("instances/")[:12]:
    instance = file[:-4]
    results[instance] = []
    for id in range(5):
        pb = init.Pb("instances/"+file, id)
        val, execTime = v.montee_timeMax(pb, fn_initialisation, fn_un_pas, timeMax=timeMax, critere=critere)
        results[instance].append((val, execTime))
        print(pb.realisabilite(pb.x))
        print(pb.b)
        print(pb.b_res)

for instance in results.keys():
    for i in range(5):
        print("instance ", instance, i, ": valeur ", results[instance][i][0], " et temps ", results[instance][i][1])

0
[36 34 38 27 33]
[5 1 0 0 0]
0
[36 37 38 48 44]
[ 1  0  0 12  0]
0
[32 37 44 35 40]
[ 2  0 21  5  8]
solution initiale non réalisable: toutes les tâches ne sont pas affectées.
0
[39 36 37 38 37]
[16  8 11 12 12]
0
[40 38 38 35 34]
[2 6 8 6 3]
0
[44 48 46 47 43 48 49 49 46 51]
[ 8  2  1  1  1  5  1 16 25 51]
0
[45 43 49 43 49 47 50 47 47 48]
[ 0 10  8  0  7  5  2  2  2  0]
0
[49 52 51 45 48 44 48 50 50 50]
[ 6 10 21  5  6  3 19  0  5 13]
0
[46 44 46 49 45 51 44 51 44 46]
[11  2  8  2  0 15  4  3  5 36]
0
[45 44 46 42 49 46 45 51 49 49]
[ 0  0  2  2  4 32 10  3 20  6]
0
[69 69 68 70 72 60 55 58 61 57]
[ 1 18 22  0  2  3  0 34  6  3]
0
[64 67 72 70 72 61 61 55 60 64]
[24  0 21  0  9  4 18  0 25  1]
0
[67 70 77 74 71 56 62 57 63 60]
[27  0 11 61 28  5  0 14  1 10]
0
[69 66 71 70 70 56 56 60 57 66]
[ 0 21  3 22 52 35  1  9  0  2]
0
[69 66 68 68 69 57 61 65 61 58]
[47 20 25  7  5  2  4  3  7  2]
0
[79 67 74 73 67 78 73 68 73 69]
[19  0  8  0  0 54  6 15  2  1]
0
[66 69 69 74 75 72 72 72 76

In [29]:
fn_initialisation = init.sol_gloutonne_2
fn_un_pas = v.un_pas_reaffectation
timeMax = 20
critere = 'max'
results2 = {}

for file in os.listdir("instances/")[:12]:
    instance = file[:-4]
    results2[instance] = []
    for id in range(5):
        pb = init.Pb("instances/"+file, id)
        val, execTime = v.montee_timeMax(pb, fn_initialisation, fn_un_pas, timeMax=timeMax, critere=critere)
        results2[instance].append((val, execTime))
        print(pb.realisabilite(pb.x))
        print(pb.b)
        print(pb.b_res)



for instance in results.keys():
    for i in range(5):
        print("instance ", instance, i, ": valeur ", results[instance][i][0], " et temps ", results[instance][i][1])

0
[36 34 38 27 33]
[ 1  1 16  4 12]
0
[36 37 38 48 44]
[ 1  0  1 15  5]
0
[32 37 44 35 40]
[ 2  4  4 10  6]
solution initiale non réalisable: toutes les tâches ne sont pas affectées.
0
[39 36 37 38 37]
[16  8 11 12 12]
0
[40 38 38 35 34]
[15  6  8  3  3]
0
[44 48 46 47 43 48 49 49 46 51]
[ 8 15  8  8  0  1  0  7  2 10]
0
[45 43 49 43 49 47 50 47 47 48]
[ 0 10  1 10  2  5  6  0  7  0]
0
[49 52 51 45 48 44 48 50 50 50]
[14 13  0  2  8  4  1  5 13  0]
0
[46 44 46 49 45 51 44 51 44 46]
[ 1  6 14  7  8 10  5  3 10  8]
0
[45 44 46 42 49 46 45 51 49 49]
[ 7  4 11 14  6  0  0  5  7  0]
0
[69 69 68 70 72 60 55 58 61 57]
[ 7  4  1  0 51 10  0  2 12  0]
0
[64 67 72 70 72 61 61 55 60 64]
[ 8 13  1  0  4  6  0 12  0 17]
0
[67 70 77 74 71 56 62 57 63 60]
[ 7  9 14 17 25  7 35  6  8  3]
0
[69 66 71 70 70 56 56 60 57 66]
[ 8  3  0 14  8 11  9  9  2  2]
0
[69 66 68 68 69 57 61 65 61 58]
[ 1  6  8  1  1 13  0 12  1  6]
0
[79 67 74 73 67 78 73 68 73 69]
[ 3 13  8  7  5  8  8  2 44  1]
0
[66 69 69 74 75 7

In [30]:
fn_initialisation = init.sol_gloutonne_2
fn_un_pas = v.un_pas_swap
timeMax = 20
critere = 'max'
results = {}

for file in os.listdir("instances/")[:12]:
    instance = file[:-4]
    results[instance] = []
    for id in range(5):
        pb = init.Pb("instances/"+file, id)
        s = time.time()
        init.sol_gloutonne_2(pb)
        e = time.time()
        results[instance].append((pb.eval(), e-s))
        print(pb.realisabilite(pb.x))
        print(pb.b)
        print(pb.b_res)

for instance in results.keys():
    for i in range(5):
        print("instance ", instance, i, ": valeur ", results[instance][i][0], " et temps ", results[instance][i][1])

0
[36 34 38 27 33]
[11  1 16  4  7]
0
[36 37 38 48 44]
[ 1  9  7 15  0]
0
[32 37 44 35 40]
[ 2  6 21  5 16]
0
[39 36 37 38 37]
[16  8 11 12 12]
0
[40 38 38 35 34]
[27  6 16  5  9]
0
[44 48 46 47 43 48 49 49 46 51]
[25  7  3  5  5 17 17 23 33 51]
0
[45 43 49 43 49 47 50 47 47 48]
[ 7 28 25 24 32 17 22  9 30 23]
0
[49 52 51 45 48 44 48 50 50 50]
[14 19 40 23 30  6 18 14 20 28]
0
[46 44 46 49 45 51 44 51 44 46]
[18 12 31 16 15 41 14 21  4 41]
0
[45 44 46 42 49 46 45 51 49 49]
[11 15  4 11  1 41 35 25 31 18]
0
[69 69 68 70 72 60 55 58 61 57]
[17 40 40 32 11 20 27 41 30  7]
0
[64 67 72 70 72 61 61 55 60 64]
[31 32 39  6 40 24 43  1 42 13]
0
[67 70 77 74 71 56 62 57 63 60]
[34 28 40 60 37 39 15 21  8 21]
0
[69 66 71 70 70 56 56 60 57 66]
[25 32 39 31 63 35 13 26  0 26]
0
[69 66 68 68 69 57 61 65 61 58]
[52 51 43 28 13  7 19 12 41 22]
0
[79 67 74 73 67 78 73 68 73 69]
[39 29 25  5 15 62 43 34 28 28]
0
[66 69 69 74 75 72 72 72 76 75]
[14 17 39 26 32 38 19 50 40 47]
0
[72 74 73 64 71 68 76 66 7

In [31]:
for i in results.keys():
    a = np.array(results[i])-np.array(results2[i])
    print(a)

[[-5.00000000e+00 -1.69706345e-03]
 [-1.00000000e+01 -9.21249390e-04]
 [-1.60000000e+01 -1.99270248e-03]
 [ 3.15000000e+02 -2.01702118e-03]
 [-1.90000000e+01 -8.67366791e-04]]
[[-6.20000000e+01 -5.46336174e-03]
 [-1.08000000e+02 -8.99696350e-03]
 [-6.00000000e+01 -5.97262383e-03]
 [-8.40000000e+01 -5.92231750e-03]
 [-8.80000000e+01 -7.01284409e-03]]
[[-1.13000000e+02 -1.09405518e-02]
 [-1.36000000e+02 -1.19330883e-02]
 [-9.90000000e+01 -9.00530815e-03]
 [-1.38000000e+02 -1.09364986e-02]
 [-1.40000000e+02 -1.29327774e-02]]
[[-1.15000000e+02 -1.59609318e-02]
 [-1.27000000e+02 -1.89528465e-02]
 [-1.48000000e+02 -2.39021778e-02]
 [-1.33000000e+02 -1.65607929e-02]
 [-1.35000000e+02 -2.09813118e-02]]
[[-1.40000000e+01 -9.97781754e-04]
 [ 0.00000000e+00 -2.46286392e-04]
 [-3.50000000e+01 -2.16269493e-03]
 [-3.00000000e+01  2.38418579e-07]
 [-2.10000000e+01 -8.90970230e-04]]
[[-2.70000000e+01 -1.02281570e-03]
 [-2.90000000e+01 -2.03514099e-03]
 [-5.10000000e+01 -1.02376938e-03]
 [-4.80000000e+